@startuml
!pragma layout smetana
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()


System_Boundary(sn, "Rust Analyzer System"){
    Component(build, "xtask", "xtask", "Rust analyzer's custom building pipeline" )
    Component(parser, "Parser", "", "Transforms one flat stream of events, into another flat stream of events" )
    Component(syntax, "Syntax", "", "Produces an interpreted syntactic tree of the given stream of events" )
    ComponentDb(basedb, "Base-db", "Salsa", "A key value store used to implement incremental and on-demand computation" )
    Component(hir, "Hir", "crates/hir-expand, crates/hir-def, crates/hir_ty", "Provides high-level object-oriented access to Rust code" )
    Component(ide_int, "Ide", "crates/ide, crates/ide-db, crates/ide-assists, crates/ide-completion, crates/ide-diagnostics, crates/ide-ssr", "Provides 'ide-centric' APIs for the rust-analyzer.")
    Component(rustanalyzer, "Rust Analyzer", "", "Implementation of the LSP for rust-analyzer.")
    Component(project, "Project", "crates/toolchain, crates/project-model, crates/flycheck", "Provide functionalities related to the project's structure and get compiler errors for the “check on save” feature")
    Component(macro, "Macros", "crates/mbe, crates/tt, crates/proc-macro-api, crates/proc-macro-srv, crates/proc-macro-srv-cli", "These crates implement macros as token tree -> token tree transforms. They are independent from the rest of the code.")
    Component(cfg, "Cfg", "crates/cfg", "This crate is responsible for parsing, evaluation and general definition of cfg attributes.")
    Component(paths, "Paths", "crates/vfs, crates/vfs-notify, crates/paths", "These crates implement a virtual file system. They provide consistent snapshots of the underlying file system and insulate messy OS paths.")
    Component(stdx, "stdx", "crates/stdx", "This crate contains various non-rust-analyzer specific utils, which could have been in std, as well as copies of unstable std items we would like to make use of already.")
    Component(profile, "Profiling", "crates/profile", "This crate contains utilities for CPU and memory profiling.")
    Component(intern, "Inter", "crates/intern", "This crate contains infrastructure for globally interning things via Arc.")
    Component(loadcargo, "Load Cargo", "crates/load-cargo", "This crate exposes several utilities for loading projects, used by the main rust-analyzer crate and other downstream consumers.")
    Component(dependencies, "Dependencies", "crates/rustc-dependencies", "This crate wraps the rustc_* crates rust-analyzer relies on and conditionally points them to mirrored crates-io releases such that rust-analyzer keeps building on stable.")
    Component(span, "Span", "crates/span", "This crate exposes types and functions related to rust-analyzer’s span for macros.")
}

Rel(rustanalyzer, ide_int, "")
Rel(ide_int, hir, "")
    Rel(ide_int, basedb, "")
Rel(hir, syntax, "")
    Rel(hir, macro, "")
    Rel(hir, cfg, "")
    Rel(hir, basedb, "")
Rel(syntax, parser, "")
Rel(rustanalyzer, loadcargo, "")
Rel(rustanalyzer, project, "")
Rel(rustanalyzer, profile, "")

Rel(basedb, intern, "")
Rel(basedb, paths, "")
Rel(basedb, span, "")
Rel(basedb, stdx, "")

@enduml


