@startuml
'!pragma layout smetana
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
skinparam nodesep 100
skinparam ranksep 200

LAYOUT_WITH_LEGEND()


System_Ext(ide_ext, "Integrated Development Environment", "Software designed to write and modify source code effectively", "Software System")
System_Ext(file_system, "Host File System", "File System of the host machine. It allows to store and retrieve files.", "Software System")

System_Boundary(sn, "Rust Analyzer System"){
    Component(parser, "parser", "Rust Component", "Implements a handwritten recursive-descent parser producing parser events." )
    ' syntax-bridge + tt have been condensed into the syntax crate
    Component(syntax, "syntax", "Rust Component", "Builds lossless and error-tolerant syntax trees over parser events." )
    ComponentDb(basedb, "base_db", "Rust Component", "Defines the base inputs and query interfaces used for incremental analysis." )
    Component(hir, "hir", "Rust Component", "Provides high-level object-oriented access to Rust code." )
    Component(ide_int, "ide", "Rust Component", "Provides 'ide-centric' APIs for the rust-analyzer.")
    Component(rustanalyzer, "rust_analyzer", "Rust Component", "Implementation of the LSP for rust-analyzer.")
    Component(project_model, "project_model", "Rust Component", "Loads and models Cargo workspaces, crates and dependencies.")
        Component(toolchain, "toolchain", "Rust Component", "This crate is responsible for discovering `cargo` and `rustc` executables on the host's machine.")
    Component(macro, "macros", "Rust Component", "Provides macro expansion infrastructure for declarative and procedural macros.")
    Component(mbe, "mbe", "Rust Component", "Provides an API for handling `macro_rules` macros.")
    Component(cfg, "cfg", "Rust Component", "This crate is responsible for parsing, evaluation and general definition of cfg attributes.")
    Component(vfs, "vfs", "Rust Component", "These crates implement a virtual file system. They provide consistent snapshots of the underlying file system and insulate messy OS paths.")
    Component(paths, "paths", "Rust Component", "Provides a thin wrapper type distinguishing between absolute and relative paths.")
    Component(stdx, "stdx", "Rust Component", "This crate contains various non-rust-analyzer specific utils, which could have been in std, as well as copies of unstable std items we would like to make use of already.")
    Component(profile, "profile", "Rust Component", "This crate contains utilities for CPU and memory profiling.")
    Component(intern, "inter", "Rust Component", "This crate contains infrastructure for globally interning things via Arc.")
    Component(loadcargo, "load_cargo", "Rust Component", "This crate exposes several utilities for loading project_models, used by the main rust-analyzer crate and other downstream consumers.")
        Component(vfs_notify, "vfs_notify", "Rust Component", "This crate provides an implementation for file watching utilities.")
    Component(dependencies, "dependencies", "Rust Component", "This crate wraps the rustc_* crates rust-analyzer relies on and conditionally points them to mirrored crates-io releases such that rust-analyzer keeps building on stable.")
    Component(span, "span", "Rust Component", "This crate exposes types and functions related to rust-analyzer’s span for macros.")
    Component(proc_macro_api, "proc_macro_api", "Rust Component", "Provides an API for executing procedural macros in a separate process.")
}

Rel(ide_ext, rustanalyzer, "Requests LSP functionality","LSP/JSON")
Rel(rustanalyzer, dependencies, "Requests dependency", "Methods call")
Rel(rustanalyzer, ide_int, "Requests analysis of Rust code", "Methods call")
Rel(rustanalyzer, proc_macro_api, "Sends macro to expand and evaluate, receives expanded result", "stdin/stdout custom messaging protocol")
Rel(ide_int, hir, "Requests semantic analysis of Rust code", "Methods call")
    Rel(ide_int, basedb, "Reads/mutates stored analysis state", "Methods call")
Rel(hir, syntax, "Requests syntactic analisys of Rust code", "Methods call")
    Rel(hir, macro, "Requests macro expansion and execution", "Methods call")
    Rel(hir, mbe, "Requests handling of macro_rules macro", "Methods call")
        Rel(mbe, syntax, "Requests syntactic analysis of Rust code", "Methods call")
    Rel(hir, cfg, "Requests Cfg parsing and evaluation", "Methods call")
    Rel(hir, basedb, "Reads stored analysis state", "Methods call")
Rel(syntax, parser, "Requests parsed model of Rust code", "Methods call")
Rel(rustanalyzer, loadcargo, "Loads Rust project", "Methods call")
    Rel(vfs_notify, loadcargo, "Notifies about file-system changes", "Events")
Rel(rustanalyzer, project_model, "Requests information about project's structure", "Methods call")
    Rel(project_model, toolchain, "Request location of `cargo` and `rustc` executables", "Methods call")

Rel(basedb, intern, "Retrieves/sends data to intern", "Methods call")
Rel(basedb, vfs, "Requests file's contents", "Methods call")
    Rel(vfs, paths, "Uses types defined in", "Methods call")
    Rel(vfs, file_system, "Reads/writes files", "OS API")
Rel(basedb, span, "requests code locations", "Methods call")
Rel(basedb, stdx, "takes utilities function", "Methods call")
Rel(rustanalyzer, profile, "gets CPU and memory profiling", "Methods call")

@enduml


