@startuml
!pragma layout smetana
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()


System_Ext(ide_ext, "Integrated Development Environment", "Software designed to write and modify source code effectively", "Software System")
System_Ext(file_system, "Host File System", "File System of the host machine. It allows to store and retrieve files.", "Software System")

System_Boundary(sn, "Rust Analyzer System"){
    Component(parser, "Parser", "Rust Component", "Transforms one flat stream of events, into another flat stream of events." )
    Component(syntax, "Syntax", "Rust Component", "Produces an interpreted syntactic tree of the given stream of events." )
    ComponentDb(basedb, "Base-db", "Rust Component", "A key value store used to implement incremental and on-demand computation." )
    Component(hir, "Hir", "Rust Component", "Provides high-level object-oriented access to Rust code." )
    Component(ide_int, "Ide", "Rust Component", "Provides 'ide-centric' APIs for the rust-analyzer.")
    Component(rustanalyzer, "Rust Analyzer", "Rust Component", "Implementation of the LSP for rust-analyzer.")
    Component(project, "Project", "Rust Component", "Provide functionalities related to the project's structure and get compiler errors for the “check on save” feature.")
    Component(macro, "Proc Macro", "Rust Component", "These crates implement macros as token tree -> token tree transforms. They are independent from the rest of the code.")
    Component(cfg, "Cfg", "Rust Component", "This crate is responsible for parsing, evaluation and general definition of cfg attributes.")
    Component(vfs, "VFS", "Rust Component", "These crates implement a virtual file system. They provide consistent snapshots of the underlying file system and insulate messy OS paths.")
    Component(stdx, "stdx", "Rust Component", "This crate contains various non-rust-analyzer specific utils, which could have been in std, as well as copies of unstable std items we would like to make use of already.")
    Component(profile, "Profiling", "Rust Component", "This crate contains utilities for CPU and memory profiling.")
    Component(intern, "Inter", "Rust Component", "This crate contains infrastructure for globally interning things via Arc.")
    Component(loadcargo, "Load Cargo", "Rust Component", "This crate exposes several utilities for loading projects, used by the main rust-analyzer crate and other downstream consumers.")
    Component(dependencies, "Dependencies", "Rust Component", "This crate wraps the rustc_* crates rust-analyzer relies on and conditionally points them to mirrored crates-io releases such that rust-analyzer keeps building on stable.")
    Component(span, "Span", "Rust Component", "This crate exposes types and functions related to rust-analyzer’s span for macros.")
}

Rel(ide_ext, rustanalyzer, "Requests LSP functionality","LSP/JSON")
Rel(rustanalyzer, dependencies, "Requests dependency", "Methods call")
Rel(rustanalyzer, ide_int, "Requests analysis of Rust code", "Methods call")
Rel(ide_int, hir, "Requests semantic analysis of Rust code", "Methods call")
    Rel(ide_int, basedb, "Reads/mutates stored analysis state", "Methods call")
Rel(hir, syntax, "Requests syntactic analisys of Rust code", "Methods call")
    Rel(hir, macro, "Requests macro expansion and execution", "Methods call")
    Rel(hir, cfg, "Requests Cfg parsing and evaluation", "Methods call")
    Rel(hir, basedb, "Reads stored analysis state", "Methods call")
Rel(syntax, parser, "Requests parsed model of Rust code", "Methods call")
Rel(rustanalyzer, loadcargo, "Loads Rust project", "Methods call")
Rel(rustanalyzer, project, "Requests information about project's structure", "Methods call")
Rel(rustanalyzer, profile, "", "Methods call")

Rel(basedb, intern, "Retrieves/sends data to intern", "Methods call")
Rel(basedb, vfs, "Requests file's contents", "Methods call")
    Rel(vfs, file_system, "Reads/writes files", "OS API")
Rel(basedb, span, "", "Methods call")
Rel(basedb, stdx, "", "Methods call")

@enduml


