@startuml
!pragma layout smetana
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_WITH_LEGEND()

Person(client, "Client", "Provider of source rust files, could be a user calling rust_analyzer directly or, more commonly, a user working with a IDE.")
System_Ext(ide_ext, "Integrated Development Environment", "Software designed to write and modify source code effectively")

System_Boundary(sb, "Rust Analyzer System"){
    Container(rustanalyzer, "Rust Analyzer", "", "Implementation of the LSP for rust-analyzer.")
    Container(xtask, "XTask", "",  "Rust analyzer's custom build system")
    ContainerDb(basedb, "Base-db", "Salsa", "A key value store used to implement incremental and on-demand computation" )
}

Rel(rustanalyzer, basedb, "Sends incremental changes")
Rel(rustanalyzer, xtask, "Binary built using")
Rel(client, ide_ext, "Provides source rust files")
Rel(ide_ext, rustanalyzer, "Request information about the code, such as compile errors, autocomplete options, ...")
Rel(rustanalyzer, ide_ext, "Produces structured semantic model of source files")
Rel(ide_ext, client, "Displays source file with semantic meaning applied")
@enduml
