@startuml
!pragma layout smetana
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
left to right direction


LAYOUT_WITH_LEGEND()

Person(client, "Client", "Provider of source Rust files, like a user working with an IDE.")
System_Ext(ide_ext, "Integrated Development Environment", "Software designed to write and modify source code effectively.", "Software System")
System_Ext(file_system, "Host File System", "File System of the host machine. It allows to store and retrieve files.", "Software System")

System_Boundary(sb, "Rust Analyzer System", "SoftwareSystem"){
    Container(rustanalyzer, "Rust Analyzer", "Cargo/Crates", "LSP client for the Rust language.")
    Container(xtask, "xtask", "xtask", "Custom builder for rust-analyzer")
}
Rel(client, ide_ext, "Provides source Rust files, uses language tooling features")
Rel(ide_ext, rustanalyzer, "Request LSP functionality", "LSP / JSON")
Rel(rustanalyzer, file_system, "Reads/writes files", "OS API")
Rel(xtask, rustanalyzer, "builds")

@enduml
